spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${HOME_URL}
    username: ${HOME_USERNAME}
    password: ${HOME_PASSWORD}

  jpa:
#    show-sql: true
    properties:
      hibernate:
#        format_sql: true
    database: mysql
#    hibernate:
#      ddl-auto: create
  kakao:
    client_id: ${KAKAO_CLIENT_ID}
    redirect_uri: ${KAKAO_REDIRECT_URI}
    client_secret: ${KAKAO_CLIENT_SECRET}

  naver:
    client_id: ${NAVER_CLIENT_ID}
    redirect_uri: ${NAVER_REDIRECT_URI}
    client_secret: ${NAVER_CLIENT_SECRET}


jwt:
  secret: ${JWT_SECRET_KEY}  # JWT 비밀 키
  access:
    token:
      expiration: 1800000  # 액세스 토큰 유효 시간 (30분)
#      expiration: 10000  # 액세스 토큰 유효 시간 (10초)
  refresh:
    token:
      expiration: 604800000  # 리프레시 토큰 유효 시간 (7일)





